### ISSUE TITLE
Format datuma pri dividendah

### ISSUE THREAD

**Issue by Vladi007** [masbug/etoro-edavki#19]
Aktualen izpis "etoro-account-statement.xlsx" ima na zavihku "Dividends" v stolpcu "Date of Payment" samo datum brez ure.
V lanskem je dejansko bila zraven tudi ura.

Pri zagonu skripte pride do spodnje napake:

Traceback (most recent call last):
  File "etoro_edavki.py", line 1105, in <module>
  File "etoro_edavki.py", line 852, in main
  File "_strptime.py", line 568, in _strptime_datetime
  File "_strptime.py", line 349, in _strptime
ValueError: time data '05/01/2022' does not match format '%d/%m/%Y %H:%M:%S'

**Comment by masbug** [comment]
eToro je spet spremenil svoj izpis... se mi zdi, da prav uživajo v večkratnem spreminjanju izpisa vsak januar.

Popravljeno v 1.5.1
