### ISSUE TITLE
Napaka ob zagonu etoro_konverzija

### ISSUE THREAD

**Issue by kumerblaz** [masbug/etoro-edavki#20]
Zdravo, pri zagonu etoro_konverzija skripte se mi pojavi ta napaka. Kaj bi lahko bilo narobe? Uporabil sem 

```
Traceback (most recent call last):
  File "etoro_edavki.py", line 1105, in <module>
  File "etoro_edavki.py", line 852, in main
TypeError: strptime() argument 2 must be str, not None
[8064] Failed to execute script etoro_edavki
```

**Comment by masbug** [comment]
Duplikat https://github.com/masbug/etoro-edavki/issues/19
