### ISSUE TITLE
error ob zagonu

### ISSUE THREAD

**Issue by oToHabibi** [masbug/etoro-edavki#41]
zgleda da "Skripta najprej avtomatsko prenese tabelo za konverzijo valut," nima več dostopa za download podatkov.,..

------------------------------------------------------------------------------
| eToro->eDavki | verzija 1.7.0
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "etoro_edavki.py", line 1103, in <module>
  File "etoro_edavki.py", line 302, in main
  File "urllib\request.py", line 240, in urlretrieve
  File "urllib\request.py", line 215, in urlopen
  File "urllib\request.py", line 521, in open
  File "urllib\request.py", line 630, in http_response
  File "urllib\request.py", line 559, in error
  File "urllib\request.py", line 492, in _call_chain
  File "urllib\request.py", line 639, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
[25988] Failed to execute script 'etoro_edavki' due to unhandled exception!
Press any key to continue . . .

![image](https://github.com/user-attachments/assets/fce23f9b-0212-4d0d-b887-76d998054ac2)

**Comment by masbug** [comment]
Ja, BSI je blokiral skriptno uporabo... očitno imajo premalo denarja, da bi njihov strežnik "zdržal" download xml skripte.

Popravljena skripta samo zate :)
https://github.com/masbug/etoro-edavki/releases/tag/v1.7.1

**Comment by oToHabibi** [comment]
thanx :) vrjamem da bo še komu prišlo prav, zdaj učitno so začeli na davčni pošiljat pozive za 2022 (jaz ga dobil 3 tedne nazaj)...

pošljem za pivo ali dva, thanx!

**Comment by masbug** [comment]
Hvala! :beers:
