### ISSUE TITLE
Error v verziji 1.7.1 (3.8.2024) xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by roksamsa** [masbug/etoro-edavki#47]
Po zagonu skripte, dobim error:

![image](https://github.com/user-attachments/assets/7052292d-efe5-44b6-a998-306634c628fa)

------------------------------------------------------------------------------
| eToro->eDavki | verzija 1.7.1 (3.8.2024)
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "etoro_edavki.py", line 1134, in <module>
  File "etoro_edavki.py", line 301, in main
  File "xml\etree\ElementTree.py", line 1203, in parse
  File "xml\etree\ElementTree.py", line 568, in parse
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
[30712] Failed to execute script 'etoro_edavki' due to unhandled exception!

**Comment by sonysunny12** [comment]
imam podobno težavo:
------------------------------------------------------------------------------
| eToro->eDavki | verzija 1.7.1 (3.8.2024)
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "etoro_edavki.py", line 1134, in <module>
  File "etoro_edavki.py", line 341, in main
  File "openpyxl_templates\table_sheet\table_sheet.py", line 379, in read
openpyxl_templates.table_sheet.table_sheet.HeadersNotFound: Header column not found on sheet 'Closed Positions' either make sure that the following headers are present 'Position ID, Action, Long / Short, Amount, Units, Open Date, Close Date, Leverage, Spread Fees (USD), Market Spread (USD), Profit(USD), Profit(EUR), FX rate at open (USD), FX rate at close (USD), Open Rate, Close Rate, Take profit rate, Stop lose rate, Overnight Fees and Dividends, Copied From, Type, ISIN, Notes'.
[18368] Failed to execute script 'etoro_edavki' due to unhandled exception!
Press any key to continue . . .

[etoro.xlsx](https://github.com/user-attachments/files/18331294/etoro.xlsx)
](url)

prosim za pomoč. Hvala, Ivan

**Comment by masbug** [comment]
Popravljeno v 4b22e5a.

**Comment by roksamsa** [comment]
Super, hvala. Testiram upam da še danes :)
